apiVersion: v1
kind: Pod
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  containers:
  - name: ollama
    image: docker.io/ollama/ollama:latest
    ports:
    - containerPort: 11434
      hostPort: 11434
      protocol: TCP
    env:
    - name: OLLAMA_HOST
      value: "0.0.0.0:11434"
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
  restartPolicy: Always
