name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Compile
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Compile
        run: sbt compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Run tests
        run: sbt test

  format:
    name: Code Formatting & Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
            target
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt', 'project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Check formatting
        run: sbt scalafmtCheck

      - name: Check scalafix
        run: sbt "scalafixAll --check"
